// =============================================================================
// Données du concours, synchronisées à la main depuis le Catalogue des projets IA (Notion).
// data.js = le seul fichier à éditer pour faire vivre le leaderboard.
//
// PROCESSES : ajouter un process validé par un team lead :
//   { id: "slug-unique-stable", name: "Nom lisible", author: "Prénom Nom", bu: "SEO", notion: "https://..." }
//   id stable et unique (relie le process à ses votes). +10 publication automatique.
//
// TEAM : votants = adresses mail @datashake.fr (clé unique anti-doublon, gère les homonymes).
//   Source = annuaire "100🗺️ Areas/datashake/Team/Annuaire datashake - emails.md".
//   { e: "email", n: "Nom — BU" } ; e = identifiant stocké, n = libellé affiché.
// =============================================================================

window.PROCESSES = [
  { id: "39c6d578-19f1-80e0-bbf5-cce6ffcdc009", name: "Analyse CRO", author: "Manon LAMARRE", bu: "SEA", notion: "https://app.notion.com/p/Analyse-CRO-39c6d57819f180e0bbf5cce6ffcdc009" },
  { id: "39c6d578-19f1-808f-a31f-dcc97ffd1fcb", name: "AppShot", author: "Ryan Curpen", bu: "Transverse", notion: "https://app.notion.com/p/AppShot-39c6d57819f1808fa31fdcc97ffd1fcb" },
  { id: "38f6d578-19f1-8039-9e58-d6ee1454e98d", name: "Audit ton compte", author: "Ryan Curpen", bu: "Transverse", notion: "https://app.notion.com/p/Audit-ton-compte-38f6d57819f180399e58d6ee1454e98d" },
  { id: "38e6d578-19f1-807d-9bf1-f4433865916a", name: "Correction de présentations Canva", author: "Elia Manguso", bu: "Transverse", notion: "https://app.notion.com/p/Correction-de-pr-sentations-Canva-38e6d57819f1807d9bf1f4433865916a" },
  { id: "3996d578-19f1-819e-bd05-c9196b07f4d7", name: "Export Notion des reportings créa (skill creative-strategy)", author: "Charlotte Cohen", bu: "CREA", notion: "https://app.notion.com/p/Export-Notion-des-reportings-cr-a-skill-creative-strategy-3996d57819f1819ebd05c9196b07f4d7" },
  { id: "3976d578-19f1-8095-bcb0-c096d362f13e", name: "MÀJ des articles de blog datashake", author: "Amaury Dormoy", bu: "SEO", notion: "https://app.notion.com/p/M-J-des-articles-de-blog-datashake-3976d57819f18095bcb0c096d362f13e" },
  { id: "3976d578-19f1-8053-9608-cd4ad2e53750", name: "Optimisation du flux -  À VALIDER", author: "Lenny", bu: "FEED", notion: "https://app.notion.com/p/Optimisation-du-flux-VALIDER-3976d57819f180539608cd4ad2e53750" },
  { id: "3846d578-19f1-8081-a47e-c48d89f5ca14", name: "Outil d’audit/check tracking pour Constat et actions à mener", author: "Julian Gillot", bu: "Tracking", notion: "https://app.notion.com/p/Outil-d-audit-check-tracking-pour-Constat-et-actions-mener-3846d57819f18081a47ec48d89f5ca14" },
  { id: "38f6d578-19f1-809a-b164-c26d10223818", name: "Quality Check Crea (Verif orthographe + Mandatory per crea)", author: "Julian Gillot", bu: "CREA", notion: "https://app.notion.com/p/Quality-Check-Crea-Verif-orthographe-Mandatory-per-crea-38f6d57819f1809ab164c26d10223818" },
  { id: "38d6d578-19f1-8151-b9a7-fc3af665eb55", name: "Skill crea-traduction-visuels", author: "Charlotte Cohen", bu: "CREA", notion: "https://app.notion.com/p/Skill-crea-traduction-visuels-38d6d57819f18151b9a7fc3af665eb55" },
  { id: "3826d578-19f1-816d-b898-df9080e5a47a", name: "Skill Creative Strategy (audit créa Motion)", author: "Charlotte Cohen", bu: "CREA", notion: "https://app.notion.com/p/Skill-Creative-Strategy-audit-cr-a-Motion-3826d57819f1816db898df9080e5a47a" },
  { id: "3786d578-19f1-81db-b271-dc7645c371e8", name: "Skill Reddit GEO (geo-reddit-com)", author: "Damien Borieu", bu: "SEO", notion: "https://app.notion.com/p/Skill-Reddit-GEO-geo-reddit-com-3786d57819f181dbb271dc7645c371e8" },
  { id: "38e6d578-19f1-8000-8538-cbc03e042084", name: "To Do Consultant Post Calls", author: "Estelle Durivault", bu: "Transverse", notion: "https://app.notion.com/p/To-Do-Consultant-Post-Calls-38e6d57819f180008538cbc03e042084" },
];

window.TEAM = [
  { e: "alex@datashake.fr", n: "Alex Kartalyan — SEA" },
  { e: "alicia@datashake.fr", n: "Alicia Kremer — SEA" },
  { e: "amaury@datashake.fr", n: "Amaury Dormoy — SEA" },
  { e: "anthony@datashake.fr", n: "Anthony Chelly — Direction" },
  { e: "arthur.p@datashake.fr", n: "Arthur Privat — CREA" },
  { e: "audrey.c@datashake.fr", n: "Audrey Chambon — SEO" },
  { e: "audrey.o@datashake.fr", n: "Audrey Ortega — RH / Admin" },
  { e: "bastien@datashake.fr", n: "Bastien Crouzat — SEA" },
  { e: "berangere@datashake.fr", n: "Bérangère Chateigner — SEA" },
  { e: "charlie@datashake.fr", n: "Charlie Limbour — SEO" },
  { e: "charlotte@datashake.fr", n: "Charlotte Cohen — CREA" },
  { e: "clara.h@datashake.fr", n: "Clara Husset — SEA" },
  { e: "clara@datashake.fr", n: "Clara Magnin — Tech / Dev" },
  { e: "clara.p@datashake.fr", n: "Clara Poncet — SEA" },
  { e: "constance@datashake.fr", n: "Constance De Beaulieau — SEA" },
  { e: "celia.l@datashake.fr", n: "Célia Lambertod — SEA" },
  { e: "damien@datashake.fr", n: "Damien Borieu — SEO" },
  { e: "dorian@datashake.fr", n: "Dorian Richard — SEA" },
  { e: "elia@datashake.fr", n: "Elia Manguso — SEA" },
  { e: "elisa.m@datashake.fr", n: "Elisa Marquette — SEA" },
  { e: "elise@datashake.fr", n: "Elise Holtzinger — CREA" },
  { e: "elodie.s@datashake.fr", n: "Elodie Soldo — SEA" },
  { e: "emilie@datashake.fr", n: "Emilie Deleigue — SEA" },
  { e: "emma@datashake.fr", n: "Emma Bonneville — Sales" },
  { e: "erwan@datashake.fr", n: "Erwan Tanguy — SEA" },
  { e: "estelle@datashake.fr", n: "Estelle Durivault — SEA" },
  { e: "florence@datashake.fr", n: "Florence Pernet — SEA" },
  { e: "felix@datashake.fr", n: "Félix Horréard — Sales" },
  { e: "heden@datashake.fr", n: "Heden Ly — Direction" },
  { e: "hugo.h@datashake.fr", n: "Hugo Husson — SEO" },
  { e: "hugo.r@datashake.fr", n: "Hugo Rabain — SEA" },
  { e: "jane@datashake.fr", n: "Jane Bonneville — SEA" },
  { e: "julian.g@datashake.fr", n: "Julian Gillot — Tracking" },
  { e: "juliette.c@datashake.fr", n: "Juliette Covat — SEA" },
  { e: "jerome@datashake.fr", n: "Jérôme Chamberlain — SEO" },
  { e: "kevin@datashake.fr", n: "Kevin Épée — CREA" },
  { e: "kiara@datashake.fr", n: "Kiara Jules-Rosette — SEO" },
  { e: "laurine@datashake.fr", n: "Laurine Hidalgo — SEA" },
  { e: "lenny@datashake.fr", n: "Lenny Lesne — SEA" },
  { e: "liam@datashake.fr", n: "Liam Laribi — CRM" },
  { e: "lilian@datashake.fr", n: "Lilian Scarpino — Sales" },
  { e: "lou@datashake.fr", n: "Lou Verplancke — CRM" },
  { e: "louis.b@datashake.fr", n: "Louis Bonjour — SEA" },
  { e: "leo@datashake.fr", n: "Léo Cottu — SEO" },
  { e: "manon.lamache@datashake.fr", n: "Manon Lamache — SEO" },
  { e: "manon.l@datashake.fr", n: "Manon Lamarre — SEA" },
  { e: "manon.m@datashake.fr", n: "Manon Masa — SEO" },
  { e: "marie-emmanuelle@datashake.fr", n: "Marie-Emmanuelle — SEA" },
  { e: "marion@datashake.fr", n: "Marion Péan — RH / Admin" },
  { e: "marlene@datashake.fr", n: "Marlène Adjovi — CREA" },
  { e: "martin.d@datashake.fr", n: "Martin Dominjon — SEA" },
  { e: "mathilde@datashake.fr", n: "Mathilde Chabert — CRM" },
  { e: "matthieu@datashake.fr", n: "Matthieu Soum — SEA" },
  { e: "mae-lys@datashake.fr", n: "Maë-Lys Budoc — SEO" },
  { e: "maelle@datashake.fr", n: "Maëlle Cohen — SEA" },
  { e: "maeva@datashake.fr", n: "Maëva Garbez — SEA" },
  { e: "maeva.m@datashake.fr", n: "Maëva Mayé — SEA" },
  { e: "melanie@datashake.fr", n: "Mélanie Cottenier — SEA" },
  { e: "nathaniel@datashake.fr", n: "Nathaniel Benhamou — CREA" },
  { e: "nicolas.h@datashake.fr", n: "Nicolas Hay — SEA" },
  { e: "olivia@datashake.fr", n: "Olivia Troehler — SEA" },
  { e: "paul@datashake.fr", n: "Paul Ferreira — SEA" },
  { e: "pierre@datashake.fr", n: "Pierre Gaudard — SEO" },
  { e: "ruben@datashake.fr", n: "Ruben Sebag — SEO" },
  { e: "ryan@datashake.fr", n: "Ryan Curpen — SEA" },
  { e: "remy@datashake.fr", n: "Rémy Bendayan — Direction" },
  { e: "sacha@datashake.fr", n: "Sacha Cardine — Sales" },
  { e: "sami.h@datashake.fr", n: "Sami Hadj-Chaouch — Tech / Dev" },
  { e: "samuel@datashake.fr", n: "Samuel Giles — SEA" },
  { e: "solene@datashake.fr", n: "Solène Perroy — SEA" },
  { e: "thibault@datashake.fr", n: "Thibaut Guisnet — SEO" },
  { e: "thomas.c@datashake.fr", n: "Thomas Casiez — SEO" },
  { e: "thomas.j@datashake.fr", n: "Thomas Jallet — CREA" },
  { e: "theo@datashake.fr", n: "Théo Steinlen — SEO" },
  { e: "theodore@datashake.fr", n: "Théodore Fresnais — RH / Admin" },
  { e: "tom@datashake.fr", n: "Tom Cayer-Barrioz — Sales" },
  { e: "tom.h@datashake.fr", n: "Tom Hamze — SEA" },
  { e: "valentin.l@datashake.fr", n: "Valentin Lefevre — SEO" },
  { e: "vincent.c@datashake.fr", n: "Vincent Coupat — Sales" },
  { e: "yanis@datashake.fr", n: "Yanis Daubié — CREA" },
  { e: "elea@datashake.fr", n: "Éléa Decostaire — SEA" },
];
